language: r
cache: packages
r:
  - oldrel
  - release
  - devel

r-packages:
  - covr
  - lintr

after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'