language: r
sudo: true
cache: packages
r:
  - oldrel
  - release
  - devel

r-packages:
  - covr

after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'install_packages("remotes")'
  - Rscript -e 'remotes::install_github("rstudio/shiny", force = TRUE)'
  - Rscript -e 'covr::codecov()'